baseurl:
title: Gouzout
subtitle: Posts by Richard Shaw
author: Richard Shaw
simple_search: http://google.com/search
description: 
name: tufte
markdown: Kramdown
kramdown:  
  input: GFM
  syntax_highlighter: rouge
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: /post/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md','LICENCE','deploy.sh']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/