# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gouzout
email: richard.shaw@bnsly.com
description: I'm interested in understanding people and think that if we could all understand each other a little better that would be a good thing. I also like technology and building useful things with it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gouzout.com" # the base hostname & protocol for your site
twitter_username: richshaw
github_username:  richshaw

# Build settings
markdown: kramdown
